function f = description2field(desc)
% Set a configuration description (array) into a property grid field.
f = uiextras.jide.PropertyGridField.empty(0, max(1, numel(desc)));
for i = 1:numel(desc)
  d = desc(i);
  t = d.type;
  try %#ok<TRYNC>
    f(i) = uiextras.jide.PropertyGridField(d.name, d.value, ...
      'Type', uiextras.jide.PropertyType(t.primitiveType, t.shape, t.domain), ...
      'Category', d.category, ...
      'DisplayName', d.displayName, ...
      'Description', d.description, ...
      'ReadOnly', d.isReadOnly, ...
      'Hidden', d.isHidden, ...
      'Preferred', d.isPreferred ...
      );
  end
end
end