classdef (Abstract) ExperimentDescription < symphonyui.core.persistent.descriptions.ExperimentDescription
  %EXPERIMENTDESCRIPTION Abstract experiment description with some key entries.
  
  methods
    
    function obj = ExperimentDescription()
      import symphonyui.core.PropertyType;
      
      prefs = admin.utils.getPreferenceMap();
      usr = prefs('user');
      stp = prefs('setup');
      inst = prefs('institution');
      lab = prefs('lab');
      
      obj.addProperty('experimenter', usr, ...
        'description', 'Who performed the experiment?', ...
        'category', 'RigId' ...
        );
      obj.addProperty('institution', inst, ...
        'description', 'Institution where the experiment was performed.', ...
        'category', 'RigId' ...
        );
      obj.addProperty('lab', lab, ...
        'description', 'Lab where experiment was performed.', ...
        'category', 'RigId' ...
        );
      obj.addProperty('setup', stp, ...
        'description', 'Which rig setup is being used?', ...
        'category', 'RigId' ...
        );
           
      
      % Try to auto-detect the appropriate rig property value
      % get the location of the +id folder then look in +rigs
      this = fileparts(fileparts(which(class(obj))));
      rigs = string(ls(fullfile(this,'+rigs','*.m')));
      rigs = strrep(rigs,'.m','');
      obj.addProperty('rigConfiguration', rigs{1}, ...
        'type', PropertyType('char','row',cellstr(rigs)),...
        'description', ...
        'Name of the rig on which the experiment was performed.', ...
        'category', 'RigId' ...
        );
    end
    
  end
end

