function createUi(obj,fig)
% CREATEUI Setup main figure components
import appbox.*;

obj.aes = { ...
  'BorderType', 'none', ...
  'FontUnits', get(fig, 'DefaultUicontrolFontUnits'), ...
  'FontName', get(fig, 'DefaultUicontrolFontName'), ...
  'FontSize', fix(get(fig, 'DefaultUicontrolFontSize')*0.85), ...
  'Padding', 3 ...
  };

set(fig, ...
  'Name', sprintf('Configurator (v%s)',obj.VERSION_), ...
  'position', screenCenter(314,300) ...
  );
obj.mainLayout = uix.VBoxFlex( ...
  'Parent', fig, ...
  'Padding', 2, ...
  'Spacing', 4 ...
  );
% initialize empty map for storing the rest of the ui elements as
% needed.
obj.controlBlocks = containers.Map();
end