function createLightPathConfiguration(obj)
import appbox.*;
if isempty(obj.lightPathDevices), return; end

% aesthetic: set padding to 2px
aes = obj.aes;
aes{find(cellfun(@(v)isequal(v,'Padding'),aes,'UniformOutput',true),1,'first')+1} = 2;

s = struct();
s.box = uix.BoxPanel( ...
  'Parent', obj.mainLayout, ...
  'Title', 'Light Path', ...
  'BackgroundColor', [1,1,1], ...
  aes{:} ...
  );
s.adjustable = uix.VBoxFlex( ...
  'Parent', s.box, ...
  'Spacing', 3, ...
  'Padding', 0 ...
  );
s.components = containers.Map();

obj.controlBlocks('lightpath') = s;
obj.populateLightPathConfiguration();
end