function createConfigurableDevicesConfiguration(obj)
import appbox.*;
if isempty(obj.configurableDevices), return; end

% aesthetic: set padding to 2px
aes = obj.aes;
aes{find(cellfun(@(v)isequal(v,'Padding'),aes,'UniformOutput',true),1,'first')+1} = 2;

s = struct();
s.box = uix.BoxPanel( ...
  'Parent', obj.mainLayout, ...
  'Title', 'Configurable Devices', ...
  aes{:} ...
  );
s.adjustable = uix.VBox( ...
  'Parent', s.box, ...
  'Spacing', 2, ...
  'Padding', 5 ...
  );
% create an empty map for storing configurableDevices
s.components = containers.Map();

obj.controlBlocks('ConfigurableDevices') = s;
obj.populateConfigurableDevicesConfiguration();
end